name: rdservice
description: This plugin can be used to consume the RD Service of biometric device via android intents.
version: 0.0.1
homepage: https://github.com/jeevareddy/rdservice.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  xml2json: ^5.3.1
  change_app_package_name: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter: 
  plugin:
    platforms:
      android:
        package: com.madali.rdservice
        pluginClass: Msf100Plugin